### ISSUE TITLE
manjaro/pidora unbound?

### ISSUE THREAD

**Issue by Mikaela** [Mikaela/shell-things#69]
Pidora didn't work with the config on Debian side and Manjaro doesn't like it either. The default config on Manjaro:

```
server:
  use-syslog: yes
  username: "unbound"
  directory: "/etc/unbound"
  trust-anchor-file: trusted-key.key
```
